apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
       containers:
        - name: nodeapp
          image: smadavan/nodehello:BUILD_NUMBER
          ports:
            - containerPort: 3000  
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
       imagePullSecrets:
        - name: regcred
      
